server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: crop-inventory-service-
          uri: lb://CROP-INVENTORY-SERVICE
          predicates:
            - name: Path
              args:
                patterns:
                  - /api/crops
                  - /api/crops/**

        - id: zone-management-service
          uri: lb://ZONE-MANAGEMENT-SERVICE
          predicates:
            - name: Path
              args:
                patterns:
                  - /api/zones
                  - /api/zones/**